version: "3"

services:
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=techtalks123
    ports:
      - 27017:27017
    container_name: tt-mongo
