version: "3"

services:
  mongo:
    image: mongo
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MONGO_INITDB_USERNAME: ${MONGO_INITDB_USERNAME}
      MONGO_INITDB_PASSWORD: ${MONGO_INITDB_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    ports:
      - 27017:27017
    container_name: tt-mongo

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8080:8080
    container_name: tt-adminer
